# Generated by Django 6.1 on 2026-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'date_start'], name='booking_boo_room_id_ec2c23_idx'),
        ),
    ]
